### ISSUE TITLE
No module named flask_bcrypt

### ISSUE THREAD

**Issue by lgcambero** [lanmaster53/honeybadger#2]
![error](https://cloud.githubusercontent.com/assets/11602705/20721176/bc62e1c0-b640-11e6-8ba0-8f6533d6f876.jpg)

Tks.

**Comment by lanmaster53** [comment]
See https://github.com/cburmeister/flask-bones/pull/22. Looks like you have an old version of Flask-Bcrypt already installed, which is more than likely causing the issue.

**Comment by lgcambero** [comment]
Any idea to be able to solve it?

**Comment by lanmaster53** [comment]
Uninstall the current version and install the latest version.
